### ISSUE TITLE
Hêy men, có 1 số chap không load được hình.

### ISSUE THREAD

**Issue by thien1590** [nhocconsr/vbook-ext#1]
Cụ thể thì có 1 số chap dùng host của sayhentai và trên app không ghép link được.
Tui báo thế thôi, khi nào rảnh tui fix được tui báo nhé :)) 

https://github.com/nhocconsr/vbook-ext/blob/master/sayhentai/src/chap.js

**Comment by nhocconsr** [comment]
> Cụ thể thì có 1 số chap dùng host của sayhentai và trên app không ghép link được.
> Tui báo thế thôi, khi nào rảnh tui fix được tui báo nhé :))
> 
> https://github.com/nhocconsr/vbook-ext/blob/master/sayhentai/src/chap.js

Ném cái link lỗi lên đây xem nào
